name: Build OPM

on:
  release:
    types: [ published ]

  push:
    branches: [ master, New ]

  # allows for manual workflow execution
  workflow_dispatch:


jobs:
  # this job prepares php sources for packaging
  build-opm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Calculate package version
        run: echo "VERSION=$(git describe --tag --abbrev=7 | sed s/-/./g)" >> $GITHUB_ENV

      - name: Build OPM package
        uses: freiconoss/action-opm-build@v1
        with:
          name: template-extended
          version: ${{ env.VERSION }}
